# Generated by Django 3.2.5 on 2021-07-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='position',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
    ]
